name: Compile Sing-box Rule Sets

on:
  workflow_dispatch:
  schedule:
    - cron: "34 0 * * 3"

jobs:
  compile-rule:
    runs-on: ubuntu-latest

    steps:
    
      - name: Initialization environment
        run: sudo -E apt -qq update && sudo -E apt -qq install make && sudo mkdir -p /workdir && sudo chown $USER:$GROUPS /workdir

      - name: Download sing-box (Linux)
        run: |
          cd /workdir
          wget https://github.com/SagerNet/sing-box/releases/download/v1.11.15/sing-box-1.11.15-linux-amd64.tar.gz -O sing-box.tar.gz
          mkdir sing-box-bin
          tar -xzf sing-box.tar.gz -C sing-box-bin
          mv sing-box-bin/sing-box-1.11.15-linux-amd64/sing-box sing-box-bin/
          chmod +x sing-box-bin/sing-box

      - name: Download rule JSON files
        run: |
          cd /workdir
          wget https://ruleset.skk.moe/sing-box/domainset/reject.json -O reject.json
          wget https://ruleset.skk.moe/sing-box/domainset/download.json -O download.json
          wget https://ruleset.skk.moe/Internal/dns_mapping_adguardhome.conf -O dns.conf

      - name: Compile rule sets
        run: |
          cd /workdir
          ./sing-box-bin/sing-box rule-set compile --output reject.srs reject.json
          ./sing-box-bin/sing-box rule-set compile --output download.srs download.json
          tail -n +6 dns.conf | grep -v 'udp://10.10.1.1:53' > dns_mapping_adguardhome_filtered.conf

      - name: Checkout
        uses: actions/checkout@master
        with:
           token: ${{ secrets.PAT_TOKEN  }}
  
      - name: Copy files
        run: |
          cp -rf /workdir/*.srs ./
          cp -rf /workdir/dns_mapping_adguardhome.conf ./
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
              
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 2
