name: Build SmartDNS Conf

on:
  workflow_dispatch:
  schedule:
    - cron: "33 0 * * *"

env:
  REPO_URL: https://github.com/felixonmars/dnsmasq-china-list
  REPO_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization environment
      run: sudo apt update && sudo apt install make && sudo mkdir -p /workdir

    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Clone source code
      run: |
        cd /workdir
        git clone $REPO_URL -b $REPO_BRANCH dnsmasq-china-list --depth 1

    - name: Compile
      run: cd /workdir/dnsmasq-china-list && make SERVER=domestic SMARTDNS_SPEEDTEST_MODE=tcp:80 smartdns-domain-rules

    - name: Compile again
      run: cd /workdir/dnsmasq-china-list && wget https://raw.githubusercontent.com/imyip/Chnroute/master/dist/chnroute/chinalist.txt -O chinalist.txt && sed -e "s|\(.*\)|domain-rules /\1/ -speed-check-mode tcp:80 -address - -nameserver domestic -ipset china|" chinalist.txt > chinalist.domain.smartdns.conf

    - name: Compile again again
      run: cd /workdir/dnsmasq-china-list && wget https://raw.githubusercontent.com/imyip/Chnroute/master/dist/chnroute/gfwlist.txt -O gfwlist.txt && sed -e "s|\(.*\)|domain-rules /\1/ -speed-check-mode none -nameserver gfw -address \#6|" gfwlist.txt > gfwlist.domain.smartdns.conf

    - name: Compile adguard rule
      run: cd /workdir/dnsmasq-china-list && make SERVER="https://dns.alidns.com/dns-query quic://dns.alidns.com tls://dns.alidns.com"  adguardhome
    
    - name: Checkout
      uses: actions/checkout@master
      with:
         token: ${{ secrets.GITHUB_TOKEN  }}

    - name: Copy files
      run: cp -rf /workdir/dnsmasq-china-list/*.domain.smartdns.conf ./ && cp -rf /workdir/dnsmasq-china-list/accelerated-domains.china.adguardhome.conf ./
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN  }}

    - name: Copy file to the target 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.MACHINE_IP }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        overwrite: true
        key: ${{ secrets.SSH_KEY }}
        source: "./accelerated-domains.china.domain.smartdns.conf,./gfwlist.domain.smartdns.conf"
        target: ${{ secrets.TARGET }}
        
    - name: Restart smartdns
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MACHINE_IP }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: docker restart smartdns

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 2
